### ISSUE TITLE
Allow providing custom path to `.tool-versions` file to look at

### ISSUE THREAD

**Issue by mkaput** [software-mansion/setup-scarb#14]
### Problem

One of our users has a Scarb project in a submodule/subdirectory of the repository. This project contains a `.tool-versions` file that the user wants to use as reference point for version selection, but there is no way to instruct the action to look for this file elsewhere than the working directory.

### Proposed Solution

Add a new input, named `tool-versions`, typed as an optional string. It will accept a path, absolute or relative to action's PWD, to the tool-versions file, that **must** exist. If provided, the action will **always** and **only** look for Scarb version in that provided path. No other deduction techniques will be applied, and inability to look for information should yield an error.

Example:

```yaml
- uses: software-mansion/setup-scarb@v1
  with:
    tool-versions: ./my-submodule/.tool-versions
```

### Notes

Most of the meat lies in this file: https://github.com/software-mansion/setup-scarb/blob/67ef98b555967b95dd7fc56ecdd1e93ce7cefdae/lib/versions.js. It is called from here: https://github.com/software-mansion/setup-scarb/blob/67ef98b555967b95dd7fc56ecdd1e93ce7cefdae/lib/main.js#L15-L22

**Comment by EvolveArt** [comment]
I'm on it 🫡

**Comment by mkaput** [comment]
Please don't forget about adding a test in our CI workflow, and also documenting this field in the readme 😃  Many thanks 😍
